'' SPIRAL

' define PAL 5
' define NTSC 6

' initialize environment
key off
color 0,0,0
screen 1
width 32

' draw the spiral...
gosub {{draw_spiral}}

' put colors in each character...
gosub {{colorize_spiral}}

' ...and start the animation!
animate_spiral:

    ' reset TIMER
	time=0
    ' do "animation"...
	j%=vpeek(8192+16)
	for i%=16 to 22
		vpoke 8192+i%,vpeek(8193+i%)
	next i%
	vpoke 8192+i%,j%

    ' waits 0,1s before return to the animation loop
	if time<{{NTSC}} then {{@}} else {{animate_spiral}}

'
' paint each character in a specific color
'
colorize_spiral:

	restore {{spiral_colors}}
	for i%=0 to 7
		read j%
		vpoke 8192+16+i%,j%
	next i%
	return

	spiral_colors:
		data &h88, &h99, &haa, &h22, &hcc, &h77, &h44, &hdd

'
' draw the spiral
'
draw_spiral:

	restore {{spiral_data}}
	j%=16

	spiral_loop:
        ' read data
		read i%
        ' exit if data is zero
		if i%=0 then return

        ' calculate position of the second spiral
		k%=i%-6144
		y%=23-k%\32
		x%=31-k% mod 32
        ' draw on screen
		vpoke i%,128+j%
		vpoke 6144+(y%*32+x%),128+(63-j%)
        ' increment color
		j%=(j%+8) and 63
		goto {{spiral_loop}}

    ' this data has been generated by another program
	spiral_data:
		data 6147,6179,6178,6177,6176,6208,6240,6241,
			\6242,6243,6275,6307,6306,6305,6304,6336,
			\6368,6369,6370,6371,6403,6435,6434,6433,
			\6432,6464,6496,6497,6498,6499,6531,6563

		data 6562,6561,6560,6592,6624,6625,6626,6627,
			\6659,6691,6690,6689,6688,6720,6752,6753,
			\6754,6755,6787,6819,6818,6817,6816,6848,
			\6880,6881,6882,6883,6883,6884,6885,6886

		data 6887,6888,6889,6890,6891,6892,6893,6894,
			\6895,6896,6897,6898,6899,6900,6901,6902,
			\6903,6904,6905,6906,6874,6842,6810,6778,
			\6746,6714,6682,6650,6618,6586,6554,6522

		data 6490,6458,6426,6394,6362,6330,6298,6266,
			\6234,6233,6232,6231,6230,6229,6228,6227,
			\6226,6225,6224,6223,6222,6221,6220,6219,
			\6218,6217,6216,6215,6247,6279,6311,6343

		data 6375,6407,6439,6471,6503,6535,6567,6599,
			\6631,6663,6695,6727,6759,6760,6761,6762,
			\6763,6764,6765,6766,6767,6768,6769,6770,
			\6771,6772,6773,6774,6742,6710,6678,6646

		data 6614,6582,6550,6518,6486,6454,6422,6390,
			\6358,6357,6356,6355,6354,6353,6352,6351,
			\6350,6349,6348,6347,6379,6411,6443,6475,
			\6507,6539,6571,6603,6635,6636,6637,6638

		data 6639,6640,6641,6642,6610,6578,6546,6514,
			\6482,6481,6480,6479,6511,6543,0
